name: Mars CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
 
    - name: Speed up maven dependency downloading
      uses: actions/cache@v4 # Caches Maven dependencies to speed up builds
      with:
        path: ~/.m2
        key: maven-${{ hashFiles('**/pom.xml') }} # Generates cache key based on `pom.xml`
        restore-keys: maven- # Allows fallback to older cache   version    
    
    - name: Build with Maven
      run: mvn clean package test
      
    - name: Run Checkstyle
      run: mvn checkstyle:check

